application: etr-cyrano
version: 1
runtime: python
api_version: 1

handlers:
- url: /a
  static_dir: templates
- url: /static
  static_dir: static
  secure: always
- url: .*
  script: main.py
  secure: always

